### ISSUE TITLE
issue showing me

### ISSUE THREAD

**Issue by ghost** [OniSensei/Gotcha-v2.1#29]
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Gotcha_v2._1.Gotcha' threw an exception. ---> System.InvalidCastException: Conversion from string "8/13/2019 3:04:28 PM" to type 'Date' is not valid.
   at Microsoft.VisualBasic.CompilerServices.Conversions.ToDate(String Value)
   at Gotcha_v2._1.Gotcha..cctor() in C:\Users\D\source\repos\Gotcha v2.1\Gotcha v2.1\Gotcha.vb:line 89
   --- End of inner exception stack trace ---
   at Gotcha_v2._1.Gotcha.Main(String[] args)

**Comment by OniSensei** [comment]
Read the error. Wrong date format in the settings.
