### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Tolo64** [OniSensei/Gotcha-v2.1#9]
here is the crash report : 

Unhandled Exception: System.TypeInitializationException: The type initializer for 'Gotcha_v2._1.Gotcha' threw an exception. ---> System.IO.FileNotFoundException: Could not find file 'C:\Users\Ziad\Desktop\Gotcha-v2.1-2.1.0.10\Gotcha-v2.1-2.1.0.10\Gotcha v2.1\bin\Debug\config\updater.ini'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path)
   at Nini.Config.IniConfigSource..ctor(String filePath)
   at Gotcha_v2._1.Gotcha..cctor()
   --- End of inner exception stack trace ---
   at Gotcha_v2._1.Gotcha.Main(String[] args)

**Comment by OniSensei** [comment]
https://github.com/OniSensei/Gotcha-v2.1/releases/download/2.1.1.1/Gotcha.Bot.v2.1.1.1.zip
Download that not the source
